spring:
  application:
    name: todo-service
  cloud:
    stream:
      bindings:
        task-schedule-out-0:
          binder: rabbit
          destination: task-schedule.exchange
          group: task-schedule
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
server:
  port: 0
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8762/eureka}
  instance:
    prefer-ip-address: true
grpc:
  server:
    port: 9090


