spring:
  application:
    name: wife-bff
server:
  port: 0
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8762/eureka}
  instance:
    prefer-ip-address: true

grpc:
  client:
    basicTask:
      address: static://localhost:9090
      negotiationType: plaintext
  server:
    port: 9091

